import { Feature } from '@a_ng_d/figmug-utils'

export const featuresScheme: Array<Feature<'BROWSE' | 'PARTICIPATE'>> = [
  {
    name: 'BROWSE',
    description: 'Browse activities',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'SERVICE',
    service: ['BROWSE'],
  },
  {
    name: 'PARTICIPATE',
    description: 'Participate in activities',
    isActive: true,
    isPro: false,
    isNew: false,
    limit: 4,
    type: 'SERVICE',
    service: ['PARTICIPATE'],
  },
  {
    name: 'ACTIVITIES',
    description: 'View all activities',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'CONTEXT',
    service: ['BROWSE'],
  },
  {
    name: 'ACTIVITIES_LOCAL',
    description: 'View local activities',
    isActive: true,
    isPro: false,
    isNew: false,
    limit: 3,
    type: 'CONTEXT',
    service: ['BROWSE'],
  },
  {
    name: 'ACTIVITIES_SELF',
    description: 'View personal activities',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'CONTEXT',
    service: ['BROWSE'],
  },
  {
    name: 'ACTIVITIES_ADD',
    description: 'Add a new activity',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'ACTIVITIES_DELETE',
    description: 'Delete an activity',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'ACTIVITIES_PUBLISH',
    description: 'Publish an activity',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'ACTIVITIES_UNPUBLISH',
    description: 'Unpublish an activity',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'ACTIVITIES_SHARE',
    description: 'Share an activity',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'ACTIVITIES_DUPLICATE',
    description: 'Duplicate an activity',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'ACTIVITIES_SEARCH',
    description: 'Search for activities',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'ACTIVITIES_OVERVIEW',
    description: 'View activity overview',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'ACTIVITIES_TEMPLATE',
    description: 'View activity template',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'ACTIVITIES_REPORT',
    description: 'Generate activity report',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'ACTIVITIES_EXPORT_ALL',
    description: 'Export all activities',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'ACTIVITIES_IMPORT',
    description: 'Import activities',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'ACTIVITIES_SETTINGS',
    description: 'Activity settings',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'ACTIVITIES_RUN',
    description: 'Run an activity',
    isActive: true,
    isPro: false,
    isNew: false,
    limit: 3,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'SETTINGS',
    description: 'General settings',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'CONTEXT',
    service: ['BROWSE'],
  },
  {
    name: 'SETTINGS_GLOBAL',
    description: 'Global settings',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['BROWSE'],
  },
  {
    name: 'SETTINGS_NAME',
    description: 'Set name',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'SETTINGS_DESCRIPTION',
    description: 'Set description',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'SETTINGS_INSTRUCTIONS',
    description: 'Set instructions',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'SETTINGS_GROUPED_BY',
    description: 'Group by settings',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['BROWSE'],
  },
  {
    name: 'SETTINGS_GROUPED_BY_PARTICIPANT',
    description: 'Group by participant',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'SETTINGS_GROUPED_BY_TYPE',
    description: 'Group by type',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'SETTINGS_TIMER',
    description: 'Timer settings',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['BROWSE'],
  },
  {
    name: 'SETTINGS_TIMER_MINUTES',
    description: 'Set timer minutes',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'SETTINGS_TIMER_SECONDS',
    description: 'Set timer seconds',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'SETTINGS_TYPES',
    description: 'Type settings',
    isActive: true,
    isPro: false,
    isNew: false,
    limit: 3,
    type: 'DIVISION',
    service: ['BROWSE'],
  },
  {
    name: 'SETTINGS_TYPES_ADD',
    description: 'Add a new type',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'SETTINGS_TYPES_REMOVE',
    description: 'Remove a type',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'SETTINGS_TYPES_NAME',
    description: 'Set type name',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'SETTINGS_TYPES_COLOR',
    description: 'Set type color',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'SETTINGS_TYPES_DESCRIPTION',
    description: 'Set type description',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'SETTINGS_TEMPLATE',
    description: 'Set template',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'SETTINGS_IMPORT',
    description: 'Import settings',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'HISTORY',
    description: 'View history',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'CONTEXT',
    service: ['BROWSE'],
  },
  {
    name: 'HISTORY_FILTER',
    description: 'Filter history',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'HISTORY_SORT',
    description: 'Sort history',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'HISTORY_EXPORT_CSV',
    description: 'Export history to CSV',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'HISTORY_EXPORT_SESSION',
    description: 'Export session history',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'HISTORY_ADD_TO',
    description: 'Add to history',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'HISTORY_DELETE',
    description: 'Delete from history',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'EXPLORE',
    description: 'Explore activities',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'CONTEXT',
    service: ['BROWSE'],
  },
  {
    name: 'PARTICIPATE_FINISH',
    description: 'Finish participation',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['PARTICIPATE'],
  },
  {
    name: 'PARTICIPATE_END',
    description: 'End participation',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['PARTICIPATE'],
  },
  {
    name: 'PARTICIPATE_INFO',
    description: 'Participation information',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['PARTICIPATE'],
  },
  {
    name: 'PARTICIPATE_INFO_IDEAS',
    description: 'Ideas information',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['PARTICIPATE'],
  },
  {
    name: 'PARTICIPATE_INFO_FACILITATOR',
    description: 'Facilitator information',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['PARTICIPATE'],
  },
  {
    name: 'PARTICIPATE_INFO_PARTICIPANTS',
    description: 'Participants information',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['PARTICIPATE'],
  },
  {
    name: 'PARTICIPATE_INFO_DESCRIPTION',
    description: 'Description information',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['PARTICIPATE'],
  },
  {
    name: 'PARTICIPATE_INFO_INSTRUCTIONS',
    description: 'Instructions information',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['PARTICIPATE'],
  },
  {
    name: 'PARTICIPATE_INFO_TYPES',
    description: 'Types information',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['PARTICIPATE'],
  },
  {
    name: 'PARTICIPATE_CREATE',
    description: 'Create participation',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['PARTICIPATE'],
  },
  {
    name: 'PARTICIPATE_CREATE_TYPE',
    description: 'Create participation type',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['PARTICIPATE'],
  },
  {
    name: 'PARTICIPATE_CREATE_IDEA',
    description: 'Create participation idea',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['PARTICIPATE'],
  },
  {
    name: 'PARTICIPATE_UPDATE',
    description: 'Update participation',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['PARTICIPATE'],
  },
  {
    name: 'PARTICIPATE_UPDATE_TYPE',
    description: 'Update participation type',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['PARTICIPATE'],
  },
  {
    name: 'PARTICIPATE_UPDATE_IDEA',
    description: 'Update participation idea',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['PARTICIPATE'],
  },
  {
    name: 'PARTICIPATE_UPDATE_REMOVE',
    description: 'Remove participation update',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['PARTICIPATE'],
  },
  {
    name: 'SHORTCUTS',
    description: 'Quick useful links',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['BROWSE', 'PARTICIPATE'],
  },
  {
    name: 'SHORTCUTS_USER',
    description: 'User menu',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['BROWSE', 'PARTICIPATE'],
  },
  {
    name: 'SHORTCUTS_HIGHLIGHT',
    description: 'Release notes',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE', 'PARTICIPATE'],
  },
  {
    name: 'SHORTCUTS_DOCUMENTATION',
    description: 'User documentation',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE', 'PARTICIPATE'],
  },
  {
    name: 'SHORTCUTS_REPOSITORY',
    description: 'Repository',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE', 'PARTICIPATE'],
  },
  {
    name: 'SHORTCUTS_EMAIL',
    description: 'Support email',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE', 'PARTICIPATE'],
  },
  {
    name: 'SHORTCUTS_FEEDBACK',
    description: 'NPS and feedback form to get NPS',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE', 'PARTICIPATE'],
  },
  {
    name: 'SHORTCUTS_REPORTING',
    description: 'Bug reports',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE', 'PARTICIPATE'],
  },
  {
    name: 'SHORTCUTS_REQUESTS',
    description: 'Feature requests',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE', 'PARTICIPATE'],
  },
  {
    name: 'SHORTCUTS_STORE',
    description: 'Other products and services',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE', 'PARTICIPATE'],
  },
  {
    name: 'SHORTCUTS_ABOUT',
    description: 'Additional information',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE', 'PARTICIPATE'],
  },
  {
    name: 'SHORTCUTS_NETWORKING',
    description: 'LinkedIn page',
    isActive: false,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE', 'PARTICIPATE'],
  },
  {
    name: 'SHORTCUTS_AUTHOR',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE', 'PARTICIPATE'],
  },
  {
    name: 'GET_PRO_PLAN',
    description: 'Pro plan subscription',
    isActive: false,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE', 'PARTICIPATE'],
  },
  {
    name: 'CONSENT',
    description: 'User vendors consent',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['BROWSE', 'PARTICIPATE'],
  },
  {
    name: 'CORRUPTED_DATA',
    description: 'Corrupted data handling',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'SERVICE',
    service: ['BROWSE', 'PARTICIPATE'],
  },
]

export const doSpecificMode = (
  proFeature?: Array<string>,
  newFeature?: Array<string>
) => {
  const features = featuresScheme.map((feature) => ({ ...feature }))
  const proFeatures = new Set(proFeature)
  const newFeatures = new Set(newFeature)

  return features.map((feature) => {
    if (proFeatures.has(feature.name)) feature.isPro = true

    if (newFeatures.has(feature.name)) feature.isNew = true

    return feature
  })
}
