import { Feature } from '@a_ng_d/figmug-utils'

export const featuresScheme: Array<Feature<'BROWSE' | 'PARTICIPATE'>> = [
  {
    name: 'BROWSE',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'SERVICE',
    service: ['BROWSE'],
  },
  {
    name: 'PARTICIPATE',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    limit: 0,
    type: 'SERVICE',
    service: ['PARTICIPATE'],
  },
  {
    name: 'ACTIVITIES',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'CONTEXT',
    service: ['BROWSE'],
  },
  {
    name: 'ACTIVITIES_LOCAL',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    limit: 3,
    type: 'CONTEXT',
    service: ['BROWSE'],
  },
  {
    name: 'ACTIVITIES_SELF',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'CONTEXT',
    service: ['BROWSE'],
  },
  {
    name: 'ACTIVITIES_ADD',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'ACTIVITIES_DELETE',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'ACTIVITIES_PUBLISH',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'ACTIVITIES_UNPUBLISH',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'ACTIVITIES_SHARE',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'ACTIVITIES_DUPLICATE',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'ACTIVITIES_SEARCH',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'ACTIVITIES_SETTINGS',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'ACTIVITIES_RUN',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    limit: 3,
    service: ['BROWSE'],
  },
  {
    name: 'SETTINGS',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'CONTEXT',
    service: ['BROWSE'],
  },
  {
    name: 'SETTINGS_GLOBAL',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['BROWSE'],
  },
  {
    name: 'SETTINGS_NAME',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'SETTINGS_DESCRIPTION',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'SETTINGS_INSTRUCTIONS',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'SETTINGS_GROUPED_BY',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['BROWSE'],
  },
  {
    name: 'SETTINGS_GROUPED_BY_PARTICIPANT',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'SETTINGS_GROUPED_BY_TYPE',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'SETTINGS_TIMER',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['BROWSE'],
  },
  {
    name: 'SETTINGS_TIMER_MINUTES',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'SETTINGS_TIMER_SECONDS',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'SETTINGS_TYPES',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    limit: 3,
    type: 'DIVISION',
    service: ['BROWSE'],
  },
  {
    name: 'SETTINGS_TYPES_ADD',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'SETTINGS_TYPES_REMOVE',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'SETTINGS_TYPES_NAME',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'SETTINGS_TYPES_COLOR',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'SETTINGS_TYPES_DESCRIPTION',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'HISTORY',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'CONTEXT',
    service: ['BROWSE'],
  },
  {
    name: 'HISTORY_FILTER',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'HISTORY_SORT',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'HISTORY_EXPORT_CSV',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'HISTORY_ADD_TO_BOARD',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'HISTORY_DELETE',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE'],
  },
  {
    name: 'EXPLORE',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'CONTEXT',
    service: ['BROWSE'],
  },
  {
    name: 'PARTICIPATE_FINISH',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['PARTICIPATE'],
  },
  {
    name: 'PARTICIPATE_END',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['PARTICIPATE'],
  },
  {
    name: 'PARTICIPATE_INFO',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['PARTICIPATE'],
  },
  {
    name: 'PARTICIPATE_INFO_IDEAS',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['PARTICIPATE'],
  },
  {
    name: 'PARTICIPATE_INFO_PARTICIPANTS',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['PARTICIPATE'],
  },
  {
    name: 'PARTICIPATE_INFO_DESCRIPTION',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['PARTICIPATE'],
  },
  {
    name: 'PARTICIPATE_INFO_INSTRUCTIONS',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['PARTICIPATE'],
  },
  {
    name: 'PARTICIPATE_INFO_TYPES',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['PARTICIPATE'],
  },
  {
    name: 'PARTICIPATE_CREATE',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['PARTICIPATE'],
  },
  {
    name: 'PARTICIPATE_CREATE_TYPE',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['PARTICIPATE'],
  },
  {
    name: 'PARTICIPATE_CREATE_IDEA',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['PARTICIPATE'],
  },
  {
    name: 'PARTICIPATE_UPDATE',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['PARTICIPATE'],
  },
  {
    name: 'PARTICIPATE_UPDATE_TYPE',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['PARTICIPATE'],
  },
  {
    name: 'PARTICIPATE_UPDATE_IDEA',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['PARTICIPATE'],
  },
  {
    name: 'PARTICIPATE_UPDATE_REMOVE',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['PARTICIPATE'],
  },
  {
    name: 'SHORTCUTS',
    description: 'Quick useful links',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['BROWSE', 'PARTICIPATE'],
  },
  {
    name: 'SHORTCUTS_USER',
    description: 'User menu',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['BROWSE', 'PARTICIPATE'],
  },
  {
    name: 'SHORTCUTS_HIGHLIGHT',
    description: 'Release notes',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE', 'PARTICIPATE'],
  },
  {
    name: 'SHORTCUTS_DOCUMENTATION',
    description: 'User documentation',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE', 'PARTICIPATE'],
  },
  {
    name: 'SHORTCUTS_REPOSITORY',
    description: 'Repository',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE', 'PARTICIPATE'],
  },
  {
    name: 'SHORTCUTS_EMAIL',
    description: 'Support email',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE', 'PARTICIPATE'],
  },
  {
    name: 'SHORTCUTS_FEEDBACK',
    description: 'NPS and feedback form to get NPS',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE', 'PARTICIPATE'],
  },
  {
    name: 'SHORTCUTS_REPORTING',
    description: 'Bug reports',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE', 'PARTICIPATE'],
  },
  {
    name: 'SHORTCUTS_REQUESTS',
    description: 'Feature requests',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE', 'PARTICIPATE'],
  },
  {
    name: 'SHORTCUTS_ABOUT',
    description: 'Additional information',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE', 'PARTICIPATE'],
  },
  {
    name: 'SHORTCUTS_NETWORKING',
    description: 'LinkedIn page',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE', 'PARTICIPATE'],
  },
  {
    name: 'PUBLICATION',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['BROWSE'],
  },
  {
    name: 'GET_PRO_PLAN',
    description: 'Pro plan subscription',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    service: ['BROWSE', 'PARTICIPATE'],
  },
  {
    name: 'CONSENT',
    description: 'User vendors consent',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    service: ['BROWSE', 'PARTICIPATE'],
  },
  {
    name: 'CORRUPTED_DATA',
    description: '',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'SERVICE',
    service: ['BROWSE', 'PARTICIPATE'],
  },
]

export const doSpecificMode = (
  proFeature?: Array<string>,
  newFeature?: Array<string>
) => {
  const features = featuresScheme.map((feature) => ({ ...feature }))
  const proFeatures = new Set(proFeature)
  const newFeatures = new Set(newFeature)

  return features.map((feature) => {
    if (proFeatures.has(feature.name)) feature.isPro = true

    if (newFeatures.has(feature.name)) feature.isNew = true

    return feature
  })
}
